option(VOXEL_GAME_ENABLE_CPPCHECK "Enable static analysis with cppcheck" OFF)
option(VOXEL_GAME_ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" OFF)
if (VOXEL_GAME_ENABLE_CPPCHECK)
    find_program(CPPCHECK cppcheck)
    if (CPPCHECK)
        set(CMAKE_CXX_CPPCHECK ${CPPCHECK} --suppress=missingInclude --enable=all
                --inconclusive -i ${CMAKE_SOURCE_DIR}/imgui/lib)
    else ()
        message(SEND_ERROR "cppcheck requested but executable not found")
    endif ()
endif ()

if (VOXEL_GAME_ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy)
    if (CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY})
    else ()
        message(SEND_ERROR "clang-tidy requested but executable not found")
    endif ()
endif ()